version: '2'
services:
  node:
    image: live-kizz
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    networks:
      default:
        aliases:
         - www.live-kizz.com.dev
    ports:
      - 3000:3000
